default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ducle
  timeout: 5000

development:
  <<: *default
  database: notification_dev

test:
  <<: *default
  database: notification_dev
