# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b9f6ca5a4d37b265d429f8a5baeb933e3a6796896602630c594d651d77a61e4feaf397aa1295da3d6b45c92337942473cdaffef0c1335dcda46bb8fd6e25581

test:
  secret_key_base: f6905c54206d273eb22c1280d1c96d9b3d7f44f0ae6704609955720275db76ac3f3117437e7dfa4527f3908b1be1f11eafb1b608403c1d67e30d8dd4112118be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
